# Generated by Django 5.2.9 on 2026-04-17 13:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='signup_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 17, 13, 37, 26, 417490, tzinfo=datetime.timezone.utc)),
        ),
    ]
