# Generated by Django 6.0.3 on 2026-04-22 09:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_page', '0002_user_signup_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='signup_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
