# Generated by Django 5.2.9 on 2026-04-22 00:00

import secrets
import string
import web_page.models.users
from django.db import migrations, models


def _make_sensor_key(length=32):
    alphabet = string.ascii_letters + string.digits
    return "".join(secrets.choice(alphabet) for _ in range(length))


def _make_unique_sensor_key(user_model, existing):
    while True:
        sensor_key = _make_sensor_key()
        if sensor_key in existing:
            continue
        if user_model.objects.filter(sensor_key=sensor_key).exists():
            continue
        existing.add(sensor_key)
        return sensor_key


def populate_sensor_key(apps, schema_editor):
    user_model = apps.get_model("web_page", "User")
    existing_keys = set(
        key for key in user_model.objects.values_list("sensor_key", flat=True) if key
    )

    for user in user_model.objects.all():
        if user.sensor_key:
            continue
        user.sensor_key = _make_unique_sensor_key(user_model, existing_keys)
        user.save(update_fields=["sensor_key"])


class Migration(migrations.Migration):

    dependencies = [
        ("web_page", "0003_alter_user_signup_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="sensor_key",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.RunPython(populate_sensor_key, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="user",
            name="sensor_key",
            field=models.CharField(
                default=web_page.models.users.generate_sensor_key,
                max_length=32,
                unique=True,
            ),
        ),
    ]
