# Generated by Django 5.2.9 on 2026-04-22 00:00

from django.db import migrations


def create_sensor_tables_for_existing_users(apps, schema_editor):
    user_model = apps.get_model("web_page", "User")
    with schema_editor.connection.cursor() as cursor:
        for user_id in user_model.objects.values_list("id", flat=True):
            table_name = f"user_sensor_data_{int(user_id)}"
            cursor.execute(
                f"""
                CREATE TABLE IF NOT EXISTS "{table_name}" (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    soil_type VARCHAR(20) NOT NULL,
                    seedling_stage VARCHAR(20) NOT NULL,
                    moi REAL NOT NULL,
                    temp REAL NOT NULL,
                    humidity REAL NOT NULL,
                    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """
            )


class Migration(migrations.Migration):

    dependencies = [
        ("web_page", "0004_user_sensor_key"),
    ]

    operations = [
        migrations.RunPython(create_sensor_tables_for_existing_users, migrations.RunPython.noop),
    ]
