# Generated by Django 5.2.9 on 2026-04-25

from django.db import migrations


def _has_column(cursor, table_name, column_name):
    cursor.execute(
        """
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = DATABASE()
          AND table_name = %s
          AND column_name = %s
        LIMIT 1
        """,
        [table_name, column_name],
    )
    return cursor.fetchone() is not None


def _has_user_id_index(cursor, table_name):
    cursor.execute(
        """
        SELECT 1
        FROM information_schema.statistics
        WHERE table_schema = DATABASE()
          AND table_name = %s
          AND column_name = 'user_id'
        LIMIT 1
        """,
        [table_name],
    )
    return cursor.fetchone() is not None


def _has_user_id_foreign_key(cursor, table_name):
    cursor.execute(
        """
        SELECT 1
        FROM information_schema.table_constraints AS tc
        JOIN information_schema.key_column_usage AS kcu
          ON tc.constraint_schema = kcu.constraint_schema
         AND tc.table_name = kcu.table_name
         AND tc.constraint_name = kcu.constraint_name
        WHERE tc.constraint_schema = DATABASE()
          AND tc.table_name = %s
          AND tc.constraint_type = 'FOREIGN KEY'
          AND kcu.column_name = 'user_id'
        LIMIT 1
        """,
        [table_name],
    )
    return cursor.fetchone() is not None


def upgrade_user_sensor_tables(apps, schema_editor):
    user_model = apps.get_model("web_page", "User")
    quoted_user_table_name = schema_editor.quote_name("web_page_user")

    with schema_editor.connection.cursor() as cursor:
        for user_id in user_model.objects.values_list("id", flat=True):
            normalized_user_id = int(user_id)
            table_name = f"user_sensor_data_{normalized_user_id}"
            quoted_table_name = schema_editor.quote_name(table_name)

            cursor.execute(
                f"""
                CREATE TABLE IF NOT EXISTS {quoted_table_name} (
                    id BIGINT AUTO_INCREMENT PRIMARY KEY,
                    user_id BIGINT NOT NULL,
                    soil_type VARCHAR(20) NOT NULL,
                    seedling_stage VARCHAR(20) NOT NULL,
                    moi DOUBLE NOT NULL,
                    temp DOUBLE NOT NULL,
                    humidity DOUBLE NOT NULL,
                    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    INDEX (user_id),
                    FOREIGN KEY (user_id) REFERENCES {quoted_user_table_name}(id) ON DELETE CASCADE
                )
                """
            )

            if not _has_column(cursor, table_name, "user_id"):
                cursor.execute(
                    f"ALTER TABLE {quoted_table_name} ADD COLUMN user_id BIGINT NULL AFTER id"
                )

            cursor.execute(
                f"UPDATE {quoted_table_name} SET user_id = %s WHERE user_id IS NULL OR user_id <> %s",
                [normalized_user_id, normalized_user_id],
            )
            cursor.execute(f"ALTER TABLE {quoted_table_name} MODIFY COLUMN user_id BIGINT NOT NULL")

            if not _has_user_id_index(cursor, table_name):
                cursor.execute(f"ALTER TABLE {quoted_table_name} ADD INDEX (user_id)")

            if not _has_user_id_foreign_key(cursor, table_name):
                cursor.execute(
                    f"""
                    ALTER TABLE {quoted_table_name}
                    ADD FOREIGN KEY (user_id) REFERENCES {quoted_user_table_name}(id)
                    ON DELETE CASCADE
                    """
                )


class Migration(migrations.Migration):

    dependencies = [
        ("web_page", "0005_create_user_sensor_tables"),
    ]

    operations = [
        migrations.RunPython(upgrade_user_sensor_tables, migrations.RunPython.noop),
    ]
